#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""
import logging
from pathlib import Path

LOG_FILE = Path.home() / "Soap/logs/code_red.log"
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(filename=str(LOG_FILE), level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
logging.info("Code red executed")
