#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""
"""CLI wrapper to run any single agent or the full SOP pipeline."""
from argparse import ArgumentParser
from importlib import import_module
import json
import logging
import time
from pathlib import Path

from codex_controller import get_soap_root, process_queue


def main() -> None:
    parser = ArgumentParser(description="Run ATI Oracle Engine phases")
    parser.add_argument(
        "phase",
        choices=["watson", "father", "mother", "arbiter", "soap", "all"],
        default="all",
        nargs="?",
        help="Which phase to run (default: all)",
    )
    parser.add_argument("--loop", action="store_true", help="Continuously run")
    parser.add_argument("--interval", type=int, default=5, help="Loop delay")
    parser.add_argument("--warm-start", action="store_true", help="Load vectors")
    args = parser.parse_args()

    root = get_soap_root()
    if args.phase == "all":
        if args.warm_start:
            from warm_start_engine import load_vectors

            load_vectors()
        while True:
            process_queue(root)
            if not args.loop:
                break
            time.sleep(args.interval)
        return

    module = import_module(f"agents.{args.phase}_phase")
    func = getattr(module, f"run_{args.phase}")

    queue_dir = root / "agent_queue"
    output_dir = root / "overlay" / "sops"
    output_dir.mkdir(parents=True, exist_ok=True)

    while True:
        for path in sorted(queue_dir.glob("*.json")):
            try:
                data = json.loads(path.read_text())
            except Exception as exc:
                logging.error("Invalid JSON %s: %s", path.name, exc)
                continue

            data = func(data)
            path.write_text(json.dumps(data, indent=2))
            if data.get("status") == "soap_complete":
                out = output_dir / path.name
                out.write_text(json.dumps(data, indent=2))
        if not args.loop:
            break
        time.sleep(args.interval)


if __name__ == "__main__":
    main()
