#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""
"""CLI wrapper to run any single agent or the full SOP pipeline."""
from argparse import ArgumentParser
from importlib import import_module
from pathlib import Path


def main() -> None:
    parser = ArgumentParser(description="Run ATI Oracle Engine phases")
    parser.add_argument(
        "phase",
        choices=["watson", "father", "mother", "arbiter", "soap", "all"],
        default="all",
        nargs="?",
        help="Which phase to run (default: all)",
    )
    args = parser.parse_args()

    if args.phase == "all":
        from codex_controller import process_queue, get_soap_root

        process_queue(get_soap_root())
        return

    module = import_module(f"agents.{args.phase}_phase")
    func = getattr(module, f"run_{args.phase}")
    func()


if __name__ == "__main__":
    main()
