#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""
"""Code-Red trigger wrapper."""
import logging
import subprocess
from pathlib import Path

from codex_controller import get_soap_root

LOG_PATH = get_soap_root() / "logs" / "trigger_code_red.log"
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(filename=str(LOG_PATH), level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def main() -> None:
    logger.info("Code-Red trigger fired")
    root = get_soap_root()
    subprocess.run(["python3", str(root / "code_red.py")], check=False)
    logger.info("Code-Red complete")


if __name__ == "__main__":
    main()
