#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""
"""Spin-Up trigger wrapper."""
import logging
import subprocess
import time
from pathlib import Path

from codex_controller import get_soap_root

LOG_PATH = get_soap_root() / "logs" / "trigger_spin_up.log"
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(filename=str(LOG_PATH), level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def main() -> None:
    logger.info("Spin-Up trigger fired")
    spin_up_script = Path(__file__).with_name("spin_up.py")
    if spin_up_script.exists():
        subprocess.run(["python3", str(spin_up_script)], check=False)
    else:
        logger.error("spin_up.py missing: %s", spin_up_script)
    logger.info("Spin-Up complete")


if __name__ == "__main__":
    main()
