#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""

import os
import subprocess
import sys
from pathlib import Path

LOG_PATH = Path.home() / "Soap/logs/trigger_force_merge.log"
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

def log(msg):
    with open(LOG_PATH, "a") as f:
        f.write(f"[merge-fix] {msg}\n")
    print(msg)

def run(cmd, check=True):
    log(f"$ {cmd}")
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    if result.stdout:
        log(result.stdout.strip())
    if result.stderr:
        log(result.stderr.strip())
    if check and result.returncode != 0:
        sys.exit(result.returncode)
    return result

def main():
    # Identify current branch
    branch = subprocess.check_output("git rev-parse --abbrev-ref HEAD", shell=True).decode().strip()
    if branch == "main":
        log("❌ You are already on main. Checkout Codex branch first.")
        return

    log(f"🔧 Preparing to force-merge '{branch}' into main...")

    run("git fetch origin")
    run("git checkout main")
    run("git pull origin main")

    run(f"git merge -X theirs {branch} || true")
    run("git add .")
    run(f"git commit -m '⚙️ Auto-merged Codex branch ({branch}) with conflict resolution'")
    run("git push origin main --force")

    log("✅ Force merge complete. Main now matches Codex system version.")

if __name__ == "__main__":
    main()
