#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""
"""Immediate full save trigger wrapper."""
import logging
import subprocess
from pathlib import Path

from codex_controller import get_soap_root

LOG_PATH = get_soap_root() / "logs" / "trigger_full_save_now.log"
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(filename=str(LOG_PATH), level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)


def main() -> None:
    logger.info("Full save now trigger fired")
    root = get_soap_root()
    subprocess.run(["python3", str(root / "full_save_now.py")], check=False)
    logger.info("Full save now complete")


if __name__ == "__main__":
    main()
