#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version
"""
"""Run all triggers in sequence for testing."""
import logging
import subprocess
from pathlib import Path

from codex_controller import get_soap_root

LOG_FILE = get_soap_root() / "logs" / "trigger_test_harness.log"
LOG_FILE.parent.mkdir(parents=True, exist_ok=True)
logging.basicConfig(filename=str(LOG_FILE), level=logging.INFO,
                    format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

TRIGGERS = [
    "+ATTENTION+",
    "+CODE-RED+",
    "+FULL_SAVE_NOW+",
    "+SPIN-DOWN+",
    "+SPIN-UP+",
]


def main() -> None:
    root = get_soap_root() / "triggers"
    for trig in TRIGGERS:
        path = root / trig
        logger.info("Running %s", trig)
        subprocess.run(["bash", str(path)], check=False)
    print("✅ System Stable")


if __name__ == "__main__":
    main()
