#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version

father_phase.py: Composition engine for ATI SOP system.
Validates logical consistency of structured SOPs and marks issues.
"""

import json
import logging
from pathlib import Path
from Soap.utils import get_soap_root

# Configuration
ROOT = get_soap_root()
QUEUE_DIR = ROOT / "agent_queue"
LOG_DIR = ROOT / "data" / "logs"
LOG_FILE = LOG_DIR / "father_phase.log"

LOG_DIR.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    filename=str(LOG_FILE),
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger(__name__)


def log(message: str, level: int = logging.INFO) -> None:
    logger.log(level, message)


def validate_logic(sop: dict) -> list:
    """Check SOP steps for clear action verbs and required fields."""
    issues = []

    if not sop.get("tools"):
        issues.append("Missing tool list.")

    proc = sop.get("procedure", [])
    if not isinstance(proc, list) or not proc:
        issues.append("Procedure steps are missing or invalid.")
    else:
        action_verbs = ["install", "remove", "check", "clean", "torque", "grease"]
        for idx, step in enumerate(proc, 1):
            if not any(verb in step.lower() for verb in action_verbs):
                issues.append(f"Step {idx} may lack a clear action: '{step}'")

    return issues


def run_father(task: dict) -> dict:
    """Validate task logic and update status accordingly."""
    try:
        log("🛠️ Father processing task")
        task["father_backup"] = json.loads(json.dumps(task))
        issues = validate_logic(task)
        if issues:
            task["logic_issues"] = issues
            task["status"] = "needs_human_review"
            log(f"⚠️ Logic issues: {issues}")
        else:
            task["status"] = "father_complete"
            log("✅ Logic validated")
    except Exception as exc:
        log(f"❌ Father error: {exc}", level=logging.ERROR)

    return task
