#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version

soap_phase.py: Final explanation agent for ATI SOP system.
Generates human-readable breakdown and technical notes for fully verified SOPs.
"""

import json
import logging
from pathlib import Path
from Soap.utils import get_soap_root

# Configuration
ROOT = get_soap_root()
QUEUE_DIR = ROOT / "agent_queue"
LOG_DIR = ROOT / "data" / "logs"
LOG_FILE = LOG_DIR / "soap_phase.log"

def setup_logging():
    LOG_DIR.mkdir(parents=True, exist_ok=True)
    logging.basicConfig(
        filename=str(LOG_FILE),
        level=logging.INFO,
        format='%(asctime)s [%(levelname)s] %(message)s'
    )

logger = logging.getLogger(__name__)

def log(message: str, level: int = logging.INFO) -> None:
    logger.log(level, message)

def explain_sop(sop: dict):
    """Build explanation and technical notes from SOP data."""
    breakdown = []
    tech_notes = []

    breakdown.append(f"📌 Purpose: {sop.get('purpose', '').strip()}")
    breakdown.append(f"📍 Scope: {sop.get('scope', '').strip()}")

    breakdown.append("🧰 Tools needed:")
    for tool in sop.get('tools', []):
        breakdown.append(f"  - {tool}")

    breakdown.append("📦 Materials needed:")
    for mat in sop.get('materials', []):
        breakdown.append(f"  - {mat}")

    if sop.get('safety'):
        breakdown.append("🛡️ Safety Notes:")
        for note in sop['safety']:
            breakdown.append(f"  ⚠️ {note}")

    breakdown.append("🛠️ Procedure Steps:")
    for i, step in enumerate(sop.get('procedure', []), 1):
        breakdown.append(f"  Step {i}: {step}")
        text = step.lower()
        if any(k in text for k in ["remove", "disassemble"]):
            tech_notes.append(f"Step {i}: Disassembly step — ensure parts are organized and secure.")
        if any(k in text for k in ["torque", "tighten"]):
            tech_notes.append(f"Step {i}: Fastening step — use torque wrench to manufacturer spec.")
        if "grease" in text:
            tech_notes.append(f"Step {i}: Lubrication — apply correct grease sparingly.")

    return breakdown, tech_notes

def run_soap(task: dict) -> dict:
    """Generate final explanation and notes."""
    setup_logging()
    try:
        if task.get("status") != "arbiter_complete":
            return task
        log("🧽 Soap processing task")
        breakdown, tech_notes = explain_sop(task)
        task["soap_backup"] = json.loads(json.dumps(task))
        task["explanation"] = breakdown
        task["tech_notes"] = tech_notes
        task["status"] = "soap_complete"
        log("✅ Soap complete")
    except Exception as exc:
        log(f"❌ Soap error: {exc}", level=logging.ERROR)
    return task
