#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version

watson_phase.py: Formatting engine for ATI SOP system.
Reads queued raw SOP JSON tasks, structures content per Watson style, and updates status.
"""

# ~/ATI_ORACLE_ENGINE/agents/watson_phase.py

import json
import logging
from pathlib import Path
from Soap.utils import get_soap_root

# Configuration
ROOT = get_soap_root()
QUEUE_DIR = ROOT / "agent_queue"
LOG_DIR = ROOT / "data" / "logs"
LOG_FILE = LOG_DIR / "watson_phase.log"

LOG_DIR.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    filename=str(LOG_FILE),
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger(__name__)


def log(message: str, level: int = logging.INFO) -> None:
    logger.log(level, message)


def structure_sop(raw_text: str) -> dict:
    """Parse raw text into a structured SOP format."""
    lines = [line.strip() for line in raw_text.splitlines() if line.strip()]
    return {
        "title": lines[0] if lines else "Untitled SOP",
        "purpose": "Describe the purpose.",
        "scope": "Define the scope here.",
        "tools": [],
        "materials": [],
        "safety": [],
        "procedure": lines[1:],
        "watson_backup": None
    }


def run_watson(task: dict) -> dict:
    """Process a single task through the Watson phase."""
    try:
        log("🧠 Watson processing task")
        structured = structure_sop(task.get("raw_text", ""))
        structured["watson_backup"] = json.loads(json.dumps(structured))
        task.update(structured)
        task["status"] = "watson_complete"
        log("✅ Watson complete")
    except Exception as exc:
        log(f"❌ Watson error: {exc}", level=logging.ERROR)
    return task

