#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version

arbiter_phase.py: Conflict resolution and orchestration agent for ATI SOP system.
Handles logic and safety validation, flags contradictions, and finalizes SOP status.
"""

# ~/ATI_ORACLE_ENGINE/agents/arbiter_phase.py

import json
import logging
from pathlib import Path
from Soap.utils import get_soap_root

# Configuration
ROOT = get_soap_root()
QUEUE_DIR = ROOT / "agent_queue"
LOG_DIR = ROOT / "data" / "logs"
LOG_FILE = LOG_DIR / "arbiter_phase.log"

LOG_DIR.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    filename=str(LOG_FILE),
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger(__name__)


def log(message: str, level: int = logging.INFO) -> None:
    logger.log(level, message)


def resolve_conflicts(sop: dict) -> bool:
    """Check for logic_issues or missing safety and mark conflicts."""
    conflicts = []
    if sop.get("logic_issues"):
        conflicts.extend(sop["logic_issues"])
    if not sop.get("safety"):
        conflicts.append("Missing safety procedures.")
    if conflicts:
        sop["conflict_fields"] = conflicts
        return False
    return True


def run_arbiter(task: dict) -> dict:
    """Resolve conflicts and finalize status."""
    try:
        status = task.get("status")
        valid_status = {"father_complete", "mother_complete", "needs_human_review"}
        if status not in valid_status:
            return task
        log("⚖️ Arbiter processing task")
        task["arbiter_backup"] = json.loads(json.dumps(task))
        if resolve_conflicts(task):
            task["status"] = "arbiter_complete"
            log("✅ Arbiter: No conflicts")
        else:
            task["status"] = "arbiter_conflict"
            log(f"⚠️ Arbiter: Conflicts found: {task.get('conflict_fields')}")
    except Exception as exc:
        log(f"❌ Arbiter error: {exc}", level=logging.ERROR)
    return task


