#!/usr/bin/env python3
"""
Author: Lucas Reynolds <lucasreynolds1988@gmail.com>
License: MIT
Generated by: Codex God Mode ∞ — ARCH Version

mother_phase.py: Safety conscience for ATI SOP system.
Appends PPE defaults and hazard-specific warnings to SOPs.
"""

import json
import logging
from pathlib import Path
from Soap.utils import get_soap_root

# Configuration
ROOT = get_soap_root()
QUEUE_DIR = ROOT / "agent_queue"
LOG_DIR = ROOT / "data" / "logs"
LOG_FILE = LOG_DIR / "mother_phase.log"
RULES_FILE = ROOT / "overlay" / "regulatory_rules.json"

# Default PPE rules
PPE_DEFAULTS = [
    "Wear safety glasses.",
    "Use mechanic gloves.",
    "Ensure work area is clean and dry."
]

# Keyword-based hazard flags
HAZARD_FLAGS = [
    ("brake", "⚠️ Brake dust may contain asbestos. Avoid blowing or dry brushing."),
    ("jack", "⚠️ Always use jack stands. Never rely solely on a jack."),
    ("grease", "⚠️ Use nitrile gloves to avoid chemical exposure."),
    ("cotter pin", "⚠️ Watch for sharp edges when removing retaining hardware."),
]

# Default regulatory schema fallback
DEFAULT_REG_RULES = {
    "General": [
        {"body": "OSHA", "rule": "29 CFR 1910"},
        {"body": "EPA", "rule": "RCRA"},
    ],
    "Aviation": [
        {"body": "FAA", "rule": "14 CFR Part 43"},
    ],
    "Medical": [
        {"body": "FDA", "rule": "21 CFR Part 820"},
        {"body": "CDC", "rule": "Disinfection Guidelines"},
    ],
}

# Setup logging
LOG_DIR.mkdir(parents=True, exist_ok=True)
logging.basicConfig(
    filename=str(LOG_FILE),
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(message)s'
)
logger = logging.getLogger(__name__)

def log(message: str, level: int = logging.INFO) -> None:
    logger.log(level, message)

def load_rules() -> dict:
    """Load regulatory rules from file or fallback."""
    if RULES_FILE.is_file():
        try:
            return json.loads(RULES_FILE.read_text())
        except Exception as exc:
            log(f"Failed to load {RULES_FILE}: {exc}", level=logging.WARNING)
    return DEFAULT_REG_RULES

def apply_safety(sop: dict) -> list:
    """Add PPE and hazard-based safety rules to SOP."""
    added = []
    sop.setdefault("safety", [])
    for rule in PPE_DEFAULTS:
        if rule not in sop["safety"]:
            sop["safety"].append(rule)
            added.append(rule)
    for step in sop.get("procedure", []):
        for keyword, warning in HAZARD_FLAGS:
            if keyword in step.lower() and warning not in sop["safety"]:
                sop["safety"].append(warning)
                added.append(warning)
    return added

def apply_regulatory_rules(sop: dict, rules: dict) -> list:
    """Add applicable regulatory references based on industry."""
    added = []
    industry = sop.get("industry", "General")
    targets = rules.get(industry, rules.get("General", []))
    sop.setdefault("regulatory_refs", [])
    for item in targets:
        ref = f"{item['body']}: {item['rule']}"
        if ref not in sop["regulatory_refs"]:
            sop["regulatory_refs"].append(ref)
            added.append(ref)
        if ref not in sop["safety"]:
            sop["safety"].append(ref)
            added.append(ref)
    if not targets:
        log(f"No regulatory rules found for {industry}", level=logging.WARNING)
    return added

def run_mother(task: dict) -> dict:
    """Apply safety and regulatory logic to SOP."""
    rules = load_rules()
    try:
        log("🛡️ Mother processing task")
        task["mother_backup"] = json.loads(json.dumps(task))
        new_rules = apply_safety(task)
        added_refs = apply_regulatory_rules(task, rules)
        if new_rules or added_refs:
            log(f"✅ Added safety info: {new_rules + added_refs}")
        else:
            log("🧼 No new safety rules needed")
        task["status"] = "mother_complete"
    except Exception as exc:
        log(f"❌ Mother error: {exc}", level=logging.ERROR)
    return task
